targets:
  $default:
    sources:
      - $package$
      - lib/**
      - lib/graphql/schema.graphql
    builders:
      artemis:
        options:
          schema_mapping:
            - output: lib/graphql/graphql_api.dart
              schema: lib/graphql/schema.graphql
              queries_glob: lib/graphql/documents/**.graphql
          scalar_mapping:
            - custom_parser_import: 'package:deesis_app/graphql/coercers.dart'
              graphql_type: date
              dart_type: DateTime